# Generated by Django 5.1 on 2024-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_image_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='categories',
            name='span',
            field=models.TextField(blank=True, null=True, verbose_name='Спан'),
        ),
    ]
